// FILE: src/components/ProductAddModal/ProductAddModal.styles.js
import { COLORS } from "../../constants/colors";

export const productAddModalStyles = {
  /* ------------------------------ MODAL ------------------------------ */
  modalContent: {
    borderRadius: "12px",
    overflow: "hidden",
    border: "none",
    boxShadow: "0 8px 24px rgba(0,0,0,0.15)",
  },
  modalBody: {
    backgroundColor: "#fafafa",
    padding: "24px 28px",
    maxHeight: "80vh",
    overflowY: "auto",
    scrollbarWidth: "none",
  },
  title: {
    margin: 0,
    fontSize: "1.35rem",
    fontWeight: 700,
    color: COLORS.text,
    lineHeight: 1.2,
  },

  /* ------------------------------ FORM ------------------------------ */
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    position: "relative",
    marginBottom: "12px",
  },
  label: {
    fontSize: "1rem",
    fontWeight: 600,
    color: COLORS.text,
    paddingBottom: "4px",
  },
  input: {
    fontSize: "1rem",
    padding: "8px 12px",
    borderRadius: "6px",
    border: `1.5px solid ${COLORS.border}`,
    outline: "none",
    transition: "border-color 0.2s ease",
  },

  /* ------------------------------ SELECT ------------------------------ */
  customSelectWrapper: {
    position: "relative",
    width: "100%",
  },
  customSelect: {
    appearance: "none",
    width: "100%",
    padding: "10px 12px",
    border: `1.5px solid ${COLORS.primary}`,
    borderRadius: "6px",
    backgroundColor: COLORS.white,
    color: COLORS.text,
    cursor: "pointer",
    fontSize: "1rem",
  },
  dropdownArrow: {
    position: "absolute",
    right: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    pointerEvents: "none",
    color: COLORS.primary,
    fontSize: "0.8rem",
  },

  /* ------------------------------ PHOTOS ------------------------------ */
  photoRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "12px",
  },
  browseButton: {
    background: COLORS.primary,
    color: COLORS.white,
    padding: "9px 16px",
    borderRadius: "6px",
    fontSize: "0.95rem",
    fontWeight: 500,
    cursor: "pointer",
    border: "none",
    position: "relative",
    transition: "all 0.25s ease",
  },
  browseButtonHover: {
    background: COLORS.text,
    transform: "translateY(-1px)",
  },
  hiddenInput: {
    position: "absolute",
    left: 0,
    top: 0,
    opacity: 0,
    cursor: "pointer",
    width: "100%",
    height: "100%",
  },
  photoGridInline: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
  },
  photoBox: {
    position: "relative",
    width: "70px",
    height: "70px",
    borderRadius: "8px",
    border: `2px solid ${COLORS.border}`,
    overflow: "hidden",
    backgroundColor: "#f2f2f2",
    transition: "transform 0.25s ease, box-shadow 0.25s ease",
  },
  photoThumb: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  photoBoxHover: {
    transform: "scale(1.05)",
    boxShadow: "0 4px 10px rgba(0, 0, 0, 0.25)",
    borderColor: COLORS.primary,
  },
  photoRemoveCross: {
    position: "absolute",
    top: "4px",
    right: "4px",
    background: COLORS.danger,
    border: "none",
    color: COLORS.white,
    borderRadius: "50%",
    width: "20px",
    height: "20px",
    fontSize: "13px",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    lineHeight: 1,
    padding: 0,
    boxShadow: "0 2px 6px rgba(0,0,0,0.2)",
    transition: "all 0.2s ease",
  },
  photoRemoveCrossHover: {
    background: "#b71c1c",
    transform: "scale(1.1)",
  },

  /* ------------------------------ VARIANTS ------------------------------ */
  variantHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: "12px",
  },
  noteText: {
    fontSize: "0.85rem",
    color: COLORS.textLight,
    flex: "1 1 auto",
  },
  unitToggleContainer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexShrink: 0,
  },
  unitToggleButton: {
    border: `1.5px solid ${COLORS.primary}`,
    backgroundColor: COLORS.white,
    color: COLORS.primary,
    fontWeight: 600,
    padding: "5px 12px",
    borderRadius: "5px",
    cursor: "pointer",
    transition: "all 0.25s ease",
    fontSize: "0.85rem",
  },
  unitToggleActive: {
    backgroundColor: COLORS.primary,
    color: COLORS.white,
    boxShadow: `0 0 0 1px ${COLORS.primary}`,
  },
  variantRow: {
    display: "flex",
    gap: "10px",
    marginBottom: "10px",
    alignItems: "center",
  },
  variantInput: {
    flex: "1 1 120px",
    fontSize: "1rem",
    padding: "8px 10px",
    borderRadius: "6px",
    border: `1.5px solid ${COLORS.border}`,
    transition: "border-color 0.2s ease",
  },
  variantRemoveBtn: {
    background: "transparent",
    border: `1.5px solid ${COLORS.danger}`,
    color: COLORS.danger,
    padding: "6px 10px",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "0.85rem",
    transition: "all 0.2s ease",
  },

  /* ------------------------------ BUTTONS ------------------------------ */
  addVariantBtn: {
    background: COLORS.primary,
    border: "none",
    color: COLORS.white,
    padding: "8px 14px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: 500,
    fontSize: "0.9rem",
    transition: "all 0.25s ease",
  },
  addVariantBtnHover: {
    background: COLORS.text,
    transform: "translateY(-1px)",
  },
  submitBtn: {
    background: COLORS.primary,
    border: "none",
    color: COLORS.white,
    padding: "10px 18px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "1rem",
    fontWeight: 600,
    alignSelf: "flex-end",
    transition: "all 0.25s ease",
  },
  submitBtnHover: {
    background: COLORS.text,
    transform: "translateY(-1px)",
  },

  /* ------------------------------ TOAST ------------------------------ */
  toastWrapper: {
    position: "fixed",
    bottom: "24px",
    right: "24px",
    zIndex: 3000,
  },
};
