// FILE: ProductAddModal.styles.js
export const productAddModalStyles = {
  modalContent: {
    borderRadius: "8px",
    overflow: "hidden",
  },
  modalBody: {
    padding: "20px 24px",
    maxHeight: "80vh",
    overflowY: "auto",
  },
  title: {
    margin: 0,
    fontSize: "1.35rem",
    fontWeight: 700,
    // assume COLORS.text exists in your constants
    color: "var(--text-color)",  
    lineHeight: 1.15,
    position: "relative",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  label: {
    fontSize: "0.95rem",
    fontWeight: 500,
    color: "#333",
  },
  input: {
    fontSize: "1rem",
    padding: "8px 12px",
    borderRadius: "4px",
    border: "1px solid #ccc",
    width: "100%",
    boxSizing: "border-box",
  },
  photoPreviewList: {
    listStyle: "none",
    padding: 0,
    margin: "8px 0 0 0",
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
  },
  photoPreviewItem: {
    background: "#f7f7f7",
    padding: "4px 8px",
    borderRadius: "4px",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    fontSize: "0.9rem",
  },
  photoRemoveBtn: {
    background: "transparent",
    border: "none",
    color: "#888",
    fontSize: "1.1rem",
    cursor: "pointer",
    lineHeight: 1,
  },
  variantRow: {
    display: "flex",
    gap: "8px",
    marginBottom: "8px",
    alignItems: "center",
  },
  variantInput: {
    fontSize: "1rem",
    padding: "6px 10px",
    borderRadius: "4px",
    border: "1px solid #ccc",
    flex: "1 1 120px",
  },
  variantRemoveBtn: {
    background: "none",
    border: "1px solid #e00",
    color: "#e00",
    padding: "4px 8px",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "0.9rem",
  },
  addVariantBtn: {
    background: "#007bff",
    border: "none",
    color: "#fff",
    padding: "6px 12px",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "0.9rem",
    alignSelf: "flex-start",
  },
  submitBtn: {
    background: "#28a745",
    border: "none",
    color: "#fff",
    padding: "10px 16px",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "1rem",
    alignSelf: "flex-end",
  },
};
