// FILE: ProductInfoContainer.styles.js
export const productInfoContainerStyles = {
  container: {
    display: "flex",
    flexDirection: "row",
    gap: "24px",
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  imageSection: {
    flex: "1 1 40%",
    cursor: "pointer",
    position: "relative",
  },
  mainImage: {
    width: "100%",
    height: "auto",
    borderRadius: "8px",
    boxShadow: "0 2px 6px rgba(0,0,0,0.1)",
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
  },
  noImage: {
    width: "100%",
    height: "220px",
    background: "#f2f2f2",
    borderRadius: "6px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#777",
  },
  infoSection: {
    flex: "1 1 55%",
  },
  name: {
    marginBottom: "6px",
    fontSize: "1.3rem",
    fontWeight: 600,
  },
  category: {
    color: "#666",
    marginBottom: "12px",
    fontSize: "0.95rem",
  },
  description: {
    marginBottom: "16px",
    fontSize: "0.95rem",
    color: "#444",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "12px",
  },
  lightboxOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 9999,
  },
  lightboxImage: {
    maxWidth: "90%",
    maxHeight: "90%",
    borderRadius: "8px",
    boxShadow: "0 0 20px rgba(255,255,255,0.2)",
  },
  arrowBtn: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    fontSize: "2.5rem",
    color: "#fff",
    background: "none",
    border: "none",
    cursor: "pointer",
    zIndex: 10000,
  },
};
