// FILE: src/pages/ProductsPage/ProductsPage.styles.js

import { COLORS } from "../../constants/colors";

export const productsPageStyles = {
  /* ---------------------------- PAGE LAYOUT ---------------------------- */
  container: {
    width: "100%",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1.25rem",
    paddingBottom: "1rem",
    boxSizing: "border-box",
  },

  /* ---------------------------- HEADER ---------------------------- */
  headerRow: {
    width: "100%",
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    marginBottom: "0.75rem",
  },
  headerLeft: {
    flex: "1 1 auto",
    paddingLeft: "5px",
  },
  titleWrapper: {
    position: "relative",
    display: "inline-block",
    paddingBottom: "6px",
  },
  title: {
    margin: 0,
    fontSize: "1.35rem",
    fontWeight: 700,
    color: COLORS.text,
    lineHeight: 1.15,
  },
  titleUnderline: {
    content: "''",
    position: "absolute",
    bottom: 0,
    left: 0,
    width: "100%",
    height: "2px",
    background: `linear-gradient(90deg, transparent 0%, ${COLORS.primary} 15%, ${COLORS.primary} 85%, transparent 100%)`,
    borderRadius: "2px",
  },

  /* ---------------------------- FILTER BAR ---------------------------- */
  headerRight: { flex: "1 1 auto" },
  filterBar: {
    display: "flex",
    alignItems: "center",
    // justifyContent: "center",
    justifyContent: "right",
    gap: "0.6rem",
    flexWrap: "wrap",
  },
  searchInput: {
    padding: "8px 12px",
    minWidth: "340px",
    border: `1.5px solid ${COLORS.primary}`,
    borderRadius: "6px",
    outline: "none",
    fontSize: "0.95rem",
    color: COLORS.text,
    backgroundColor: COLORS.white,
    transition: "all 0.2s ease",
  },
  searchBtn: {
    padding: "8px 14px",
    fontSize: "0.95rem",
    borderRadius: "6px",
    border: `1.5px solid ${COLORS.primary}`,
    backgroundColor: COLORS.primary,
    color: COLORS.white,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  clearBtn: {
    padding: "8px 14px",
    fontSize: "0.95rem",
    borderRadius: "6px",
    border: `1.5px solid ${COLORS.primary}`,
    backgroundColor: "transparent",
    color: COLORS.primary,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  customSelectWrapper: {
    position: "relative",
    width: "220px",
  },
  customSelect: {
    appearance: "none",
    width: "100%",
    padding: "8px 12px",
    border: `1.5px solid ${COLORS.primary}`,
    borderRadius: "6px",
    backgroundColor: COLORS.white,
    color: COLORS.text,
    cursor: "pointer",
    fontSize: "0.95rem",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    overflow: "hidden",
  },
  dropdownArrow: {
    position: "absolute",
    right: "10px",
    top: "50%",
    transform: "translateY(-50%)",
    pointerEvents: "none",
    color: COLORS.primary,
    fontSize: "0.75rem",
  },

  /* ---------------------------- GRID ---------------------------- */
  gridContainer: {
    width: "100%",
    flex: "1 1 auto",
    display: "grid",
    justifyItems: "start",
    alignItems: "start",
    gap: "1.5rem",
  },

  /* ---------------------------- PAGINATION ---------------------------- */
  paginationRow: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    marginTop: "auto",
    paddingTop: "1rem",
  },
  paginationContainer: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: "0.35rem",
    alignItems: "center",
    maxWidth: "90vw",
  },
  paginationBtn: {
    minWidth: "38px",
    padding: "7px 10px",
    borderRadius: "8px",
    border: `1px solid ${COLORS.border}`,
    background: "transparent",
    color: COLORS.text,
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "0.95rem",
    transition: "all 0.15s ease",
  },
  paginationBtnActive: {
    background: COLORS.primary,
    color: "#fff",
    borderColor: COLORS.primary,
  },
  paginationBtnDisabled: {
    opacity: 0.45,
    cursor: "not-allowed",
  },

  /* ---------------------------- EMPTY / LOADING / ERROR ---------------------------- */
  emptyState: {
    width: "100%",
    minHeight: "40vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    color: COLORS.textLight,
    textAlign: "center",
    padding: "2rem 1rem",
  },
  emptyText: {
    fontSize: "1.1rem",
    marginBottom: "1rem",
  },
  addProductBtn: {
    padding: "0.6rem 1.4rem",
    fontWeight: 600,
    borderRadius: "6px",
    border: `1.5px solid ${COLORS.primary}`,
    backgroundColor: COLORS.primary,
    color: COLORS.white,
    fontSize: "1rem",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  networkErrorContainer: {
    width: "100%",
    minHeight: "50vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    color: COLORS.text,
    padding: "2rem 1rem",
  },
  networkErrorTitle: {
    fontSize: "1.25rem",
    fontWeight: 700,
    color: COLORS.danger,
    marginBottom: "0.5rem",
  },
  networkErrorText: {
    color: COLORS.textLight,
    marginBottom: "1rem",
  },
  retryBtn: {
    padding: "0.5rem 1.25rem",
    fontSize: "1rem",
    borderRadius: "6px",
    fontWeight: 600,
    backgroundColor: COLORS.primary,
    color: COLORS.white,
    border: `1px solid ${COLORS.primary}`,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  loadingContainer: {
    width: "100%",
    minHeight: "60vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    color: COLORS.text,
  },
  loadingSpinner: {
    width: "42px",
    height: "42px",
    border: `4px solid ${COLORS.border}`,
    borderTop: `4px solid ${COLORS.primary}`,
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
    marginBottom: "1rem",
  },
  loadingText: {
    fontSize: "1.25rem",
    fontWeight: 600,
    color: COLORS.textLight,
  },
};
