// FILE: src/pages/Orders/OrdersPage.styles.js

import { COLORS } from "../../constants/colors";

export const ordersPageStyles = {
  container: {
    width: "100%",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1.25rem",
    paddingBottom: "1rem",
    boxSizing: "border-box",
  },

  headerRow: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "1.25rem",
    flexWrap: "wrap",
    gap: "1rem",
  },

  /* LEFT: My Orders */
  titleWrapper: {
    position: "relative",
    display: "inline-block",
    paddingBottom: "6px",
  },
  title: {
    margin: 0,
    fontSize: "1.35rem",
    fontWeight: 700,
    color: COLORS.text,
    lineHeight: 1.15,
  },
  titleUnderline: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: "100%",
    height: "2px",
    background: `linear-gradient(90deg, transparent 0%, ${COLORS.primary} 15%, ${COLORS.primary} 85%, transparent 100%)`,
    borderRadius: "2px",
  },

  /* RIGHT: Filters */
  filterBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: "0.6rem",
  },
  searchInput: {
    padding: "8px 12px",
    minWidth: "310px",
    border: `1.5px solid ${COLORS.primary}`,
    borderRadius: "6px",
    outline: "none",
    fontSize: "0.95rem",
    color: COLORS.text,
    backgroundColor: COLORS.white,
    transition: "all 0.2s ease",
  },
  searchBtn: {
    padding: "8px 14px",
    fontSize: "0.95rem",
    borderRadius: "6px",
    border: `1.5px solid ${COLORS.primary}`,
    backgroundColor: COLORS.primary,
    color: COLORS.white,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  clearBtn: {
    padding: "8px 14px",
    fontSize: "0.95rem",
    borderRadius: "6px",
    border: `1.5px solid ${COLORS.primary}`,
    backgroundColor: "transparent",
    color: COLORS.primary,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  dateRangeWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "0.35rem",
  },
  dateLabel: {
    fontSize: "0.9rem",
    color: COLORS.textLight,
  },
  dateInput: {
    width: "145px",
    height: "41px",
    padding: "7px 10px",
    border: `1.5px solid ${COLORS.primary}`,
    borderRadius: "6px",
    outline: "none",
    fontSize: "0.9rem",
    color: COLORS.text,
    backgroundColor: COLORS.white,
    transition: "border-color 0.2s ease",
  },
  customSelectWrapper: { position: "relative", width: "200px" },
  customSelect: {
    appearance: "none",
    width: "100%",
    padding: "8px 12px",
    border: `1.5px solid ${COLORS.primary}`,
    borderRadius: "6px",
    backgroundColor: COLORS.white,
    color: COLORS.text,
    cursor: "pointer",
    fontSize: "0.95rem",
  },
  dropdownArrow: {
    position: "absolute",
    right: "10px",
    top: "50%",
    transform: "translateY(-50%)",
    pointerEvents: "none",
    color: COLORS.primary,
    fontSize: "0.75rem",
  },
  gridContainer: {
    width: "100%",
    flex: "1 1 auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1.5rem",
  },
};
